<h2><i class="fa fa-shopping-cart"></i> Passer une commande</h2>

<form data-order-step="run" id="order-form"class="generic-form">

    <!-- Champ caché stockant le prix de vente du produit alimentaire sélectionné -->
    <input type="hidden" name="salePrice">

    <aside class="error-message hidden">
        <h3><i class="fa fa-warning"></i> Il y a <em class="total-error-count">1</em> erreur(s) dans le formulaire !</h3>
        <p></p>
    </aside>

    <fieldset>
        <legend>Ajouter un article</legend>
        <ul>
            <li>
              <label for="meal">Nom :</label>
                <select id="meal" name="meal">
                  <?php foreach($menu as $value) {?>
                    <option value="<?=$value['Id']?>"><?=$value['Name']?></option>
                  <?php } ?>
                </select>
                <article id="meal-details" class="meal-details no-left-label">
                    <img src="" alt="Photo du produit">
                    <p></p>
                    <span><strong></strong></span>
                </article>
            </li>
            <li>
                <label for="quantity">Quantité :</label>
                <input id="quantity" class="quantity" type="text" maxlength="2" name="quantity" data-name="Quantité" data-type="positive-integer" data-required>
            </li>
            <li>
                <button id="validateMeal" class="button button-primary no-left-label" type="submit">Ajouter</button>
            </li>
        </ul>
    </fieldset>

    <fieldset>
        <legend>Récapitulatif de la commande</legend>
        <h2 id="empty-basket" class="hidden">Votre panier est vide pour le moment !</h2>
        <section id="order-summary" class="hidden">
        </section>
    </fieldset>
</form>
<ul class="link-list">
    <li>
        <a href="<?= $requestUrl ?>/order/validate/"><button class="button button-primary">Valider la commande</button></a>
        <a href="<?= $requestUrl ?>/" class="button button-cancel small">Annuler</a>
    </li>
</ul>
<script src="<?= $wwwUrl ?>/js/classes/OrderForm.class.js"></script>
<script src="<?= $wwwUrl ?>/js/classes/BasketSession.class.js"></script>
