<!DOCTYPE html>
<html lang="fr" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="css/style.css">
    <title>3WA Painter</title>
  </head>
  <body>
    <h1>3WA Painter</h1>
    <svg width="800" height="800" version="1.1" xmlns="http://www.w3.org/2000/svg">
      <!--<?= $rec ?>
      <?= $sq ?>
      <?= $cerc ?>
      <?= $ell ?>
      <?= $tri ?>-->
      <?php foreach ($result as $value) {?>
         <?= $value ?>
      <?php } ?>
    </svg>
  </body>
</html>
