<div class="container">
  <h2 class="my-4 text-center">Proceed with your payment</h2>
  <form action="<?= $requestUrl ?>/charge?id=<?=$orderId?>" method="post" id="payment-form">
    <div class="form-row">
      <div id="card-element" class="form-control ">
        <!-- A Stripe Element will be inserted here. -->
        
      </div>

      <!-- Used to display form errors. -->
      <div id="card-errors" role="alert"></div>
    </div>

    <button>Submit Payment</button>
  </form>
</div>
<script src="https://js.stripe.com/v3/"></script>
<script src="<?= $wwwUrl ?>/js/charge.js"></script>
