
<h2><i class="fa fa-cogs"></i>Panneau d'administration</h2>

<nav>
  <a href="add_post.php">Rédiger un nouvel article</a>
</nav>

<table>
  <caption>Liste des articles</caption>
  <thead>
    <tr>
      <th>Titre</th>
      <th>Article</th>
      <th>Auteur</th>
      <th>Catégorie</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($adminPost as $value): ?>
      <tr>
        <td><?=$value['Title']?></td>
        <td><?=$value['Content']?></td>
        <td><?=$value['FirstName']?> <?=$value['LastName']?></td>
        <td><?=$value['Name']?></td>
        <td>
          <a class="edit" href="edit_post.php?id=<?=$value['Id']?>"><i class="fa fa-pencil"></i></a>
          <a class="remove" href="delete.php?id=<?=$value['Id']?>"><i class="fa fa-remove"></i></a>
        </td>
      </tr>
    <?php endforeach; ?>
  </tbody>
</table>
