
<h2><i class="fa fa-cogs"></i>Panneau d'administration</h2>

<nav>
  <a href="add_post.php">Rédiger un nouvel article</a>
</nav>

<table>
  <caption>Liste des articles</caption>
  <thead>
    <tr>
      <th>Titre</th>
      <th>Article</th>
      <th>Auteur</th>
      <th>Catégorie</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>      
      <td><a class="edit" href="edit_post.php?id=7"><i class="fa fa-pencil"></i></a> <a class="remove" href="delete_post.php?id=7"><i class="fa fa-remove"></i></a></td>
    </tr>
  </tbody>
</table>
