<a href="#"><h2><i class="fa fa-home"></i> Accueil</h2></a>

<ul class="post-list">

  <?php foreach ($titles as $title): ?>
    <li class="post">
      <h3>
      <i class="fa fa-hand-o-right"></i>&nbsp;
        <!-- Lien vers article de blog détaillé avec les commentaires -->
            <a href="show_post.php?Id=<?=$title['Id']?>" title="Consulter l'article">
              <?=$title['Title']?>
            </a>
      </h3>
      <!-- Seul un extrait de l'article du blog est affiché -->
        <article>
          <?=$title['Content']?>[...]
        </article>
      <small>
        Rédigé par <?=$title['FirstName'].' '.$title['LastName']?> le <?=$title['CreationDate']?>
      </small>
    </li>
  <?php endforeach; ?>
</ul>
