<h2><i class="fa fa-home"></i> Accueil</h2>

<ul class="post-list">
            <li class="post">
            <h3>
                <i class="fa fa-hand-o-right"></i>&nbsp;
                <!-- Lien vers article de blog détaillé avec les commentaires -->
                <a href="show_post.php?id=8" title="Consulter l'article">
                    Diner amis
                </a>
            </h3>
            <!-- Seul un extrait de l'article du blog est affiché -->
            <article></article>
            <small>
            </small>
        </li>
    </ul>
