<a href="#"><h2><i class="fa fa-home"></i> Accueil</h2></a>

<ul class="post-list">

  <?php foreach ($titles as $title): ?>
    <li class="post">
      <h3>
      <i class="fa fa-hand-o-right"></i>&nbsp;
        <!-- Lien vers article de blog détaillé avec les commentaires -->
            <a href="show_post.php?id=<?=$title['Id']?>" title="Consulter l'article">
              <?= htmlspecialchars($title['Title'])?>
            </a>
      </h3>
      <!-- Seul un extrait de l'article du blog est affiché -->
        <article>
          <?= substr(htmlspecialchars($title['Content']), 0, 100)?>&nbsp;[...]
        </article>
      <small>
        Rédigé par <?= htmlspecialchars($title['FirstName']).' '.htmlspecialchars($title['LastName'])?> le <?=htmlspecialchars($title['CreationDate'])?>
      </small>
    </li>
  <?php endforeach; ?>
</ul>
