<form class="generic-form" action ="login.php" method="POST">
	<fieldset>
		<legend><i class="fas fa-forward"></i> Se connecter</legend>
		<ul>
			<li>
				<label for="Mail">Email :</label>
				<input type="text" placeholder="mail" name="Mail">
			</li>
			<li>
				<label for="Password">Mot de Pass :</label>
				<input type="text" placeholder="password" name="Password">
			</li>
			<li>
					<button class="button button-primary" type="submit">Se connecter</button>
					<a class="button button-cancel" href="index.php">Annuler</a>
			</li>
		</ul>
	</fieldset>
</form>
