
<h2><i class="fas fa-pencil-alt"></i>Enregistrez vous</h2>

<form class="generic-form" action ="register.php" method="POST">
  <fieldset>
    <legend><i class="fas fa-sticky-note"></i></i>  Nouvel utilisateur</legend>
    <ul>
      <li>
        <label for="FirstName">PréNom :</label>
        <input type="text" placeholder="prénom" name="FirstName">
      </li>
      <li>
        <label for="lastName">Nom :</label>
        <input type="text" placeholder="nom" name="LastName">
      </li>
      <li>
        <label for="NickName">Pseudo :</label>
        <input type="text" placeholder="pseudo" name="NickName">
      </li>
      <li>
        <label for="Mail">Email :</label>
        <input type="text" placeholder="mail" name="Mail">
      </li>
      <li>
        <label for="Password">Mot de Pass :</label>
        <input type="text" placeholder="password" name="Password">
      </li>
      <li>
          <button class="button button-primary" type="submit">Bienvenue</button>
          <a class="button button-cancel" href="index.php">Annuler</a>
      </li>
    </ul>
  </fieldset>
</form>
