        <!-- Chargement du template PHTML spécifié par le programme PHP -->
        <!-- Page d'article de blog détaillé avec les commentaires -->
<h2><i class="fa fa-file-text-o"></i> Article</h2>

<!-- Article du blog -->
<section class="post">
    <h3></h3>
    <article></article>
    <small>
    </small>
</section>

<hr>

<!-- Liste des commentaires de l'article du blog -->
<ul class="comment-list">
            <li class="comment">
            <h4><i class="fa fa-comment"></i> Rédigé par </h4>
            <article></article>
        </li>
    </ul>

<hr>

<!-- Formulaire de saisie d'un nouveau commentaire pour cet article -->
<form class="generic-form" action="add_comment.php" method="POST">

    <!-- Utilisation d'un champ caché pour spécifier à quel article rattacher le commentaire -->
    <input type="hidden" name="postId" value="11">

    <fieldset>
        <legend><i class="fa fa-comment-o"></i> Nouveau commentaire</legend>
        <ul>
            <li>
                <label for="nickName">Pseudo :</label>
                <input type="text" id="nickName" name="nickName">
            </li>
            <li>
                <label class="textarea" for="contents">Commentaire :</label>
                <textarea id="contents" name="contents" rows="5"></textarea>
            </li>
            <li>
                <button class="button button-primary" type="submit">Ajouter</button>
                <a class="button button-cancel" href="index.php">Annuler</a>
            </li>
        </ul>
    </fieldset>
</form>
