<!DOCTYPE html>
<html lang="fr" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="normalize.css">
    <link rel="stylesheet" href="order-form.css">
    <title>Order-Form</title>
  </head>
  <body>
    <h1>Bons de commande</h1>
    <div class="link">
      <a href="table.php">Retourner à l'accueil</a>
    </div>
        <article class="order-form-customer">
            <h2><?= $customer['customerName'] ?></h2>
            <h3><?= $customer['contactFirstName'] ?> <?= $customer['contactLastName'] ?></h3>
            <p><?= $customer['addressLine1'] ?></p>
            <p><?= $customer['addressLine2'] ?></p>
            <p><?= $customer['city'] ?></p>
        </article>
        <hr>
        <section>
          <h2>Bon de commande n° <?=$_GET['orderNumber']?></h2>
          <table>
            <thead>
              <th>Produit</th>
              <th class="money-column">Prix Unitaire</th>
              <th>Quantité</th>
              <th class="money-column">Prix Total</th>
            </thead>
            <tfoot>
                <tr>
                    <th colspan="3">Montant Total HT</th>
                    <th><?= number_format($totalAmount, 2) ?> €</th>
                </tr>
                <tr>
                    <th colspan="3">TVA (20 %)</th>
                    <th><?= number_format($totalAmount * 0.20, 2) ?> €</th>
                </tr>
                <tr>
                    <th colspan="3">Montant Total TTC</th>
                    <!-- Multiplier par 1.20 revient à ajouter 20% à une variable -->
                    <th><?= number_format($totalAmount * 1.20, 2) ?> €</th>
                </tr>
            </tfoot>
            <tbody>
              <?php foreach ($product as $invoice): ?>
                <tr>
                  <td><?= $invoice['productName'] ?></td>
                  <td class="money-column"><?= number_format($invoice['priceEach'], 2) ?> €</td>
                  <td><?= $invoice['quantityOrdered'] ?></td>
                  <td class="money-column"><?= number_format($invoice['price'], 2) ?> €</td>
                </tr>
              <?php endforeach ?>
            </tbody>
          </table>
        </section>
  </body>
</html>
