<!DOCTYPE html>
<html lang="fr" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="normalize.css">
    <link rel="stylesheet" href="table.css">
    <title>Table - Customers</title>
  </head>
  <body>
    <h1>Bons de commande</h1>
    <h2>Liste des commandes</h2>
    <table>
      <thead>
        <th>Commande</th>
        <th>Date de la commande</th>
        <th>Date de livraison</th>
        <th>Statut</th>
      </thead>
      <tbody>
          <?php foreach ($orders as $order): ?>
          <tr>
            <td><a href="order-form.php?orderNumber=<?= $order['orderNumber'] ?>"><?= $order['orderNumber'] ?></a></td>
            <td><?= $order['orderDate'] ?></td>
            <td><?= $order['shippedDate'] ?></td>
            <td><?= $order['status'] ?></td>
          </tr>
          <?php endforeach ?>

      </tbody>
    </table>

  </body>
</html>
