<!DOCTYPE html>
<html lang="fr" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Frame</title>
  </head>
  <body>
    <header>
    	<a href="<?=$requestUrl?>">home</a>
    	<a href="<?=$requestUrl?>?page=login">login</a>
    	<a href="<?=$requestUrl?>?page=register">register</a>
    </header>
    <div>
    	<?php include $page.'/'.$page.'View.phtml'; ?>
    </div>
    <footer>
    	<p>Voici mon footer</p>
    </footer>
  </body>
</html>
